[package]
name = "sync-committee-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]


[dependencies]
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", branch = "main", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main", default-features = false }
hex-literal = { package = "hex-literal", version = "0.3.3", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
    "derive"
] }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    'codec/std'
]
testing = []
