[package]
name = "sync-committee-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]


[dependencies]
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", rev = "d3fe0ad76613b52cdfbdea7c317ecdc35f271e4f", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", rev = "2e28a8800787392045fb3f8f1eaef6c65a8600d7", default-features = false }
hex-literal = { package = "hex-literal", version = "0.3.3", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
    "derive"
] }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    'codec/std'
]
testing = []
