[package]
name = "sync-committee-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]

[dependencies]
sync-committee-primitives = { path= "../primitives", default-features = false }
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", rev = "d3fe0ad76613b52cdfbdea7c317ecdc35f271e4f", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", rev = "2e28a8800787392045fb3f8f1eaef6c65a8600d7", default-features = false }
milagro_bls = { git = "https://github.com/sigp/milagro_bls", default-features = false }
log = { version = "0.4.17", default-features = false }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    "milagro_bls/std",
    "log/std"
]
testing = ["sync-committee-primitives/testing"]
