[package]
name = "sync-committee-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs"]

[dependencies]
sync-committee-primitives = { path= "../primitives", default-features = false }
ethereum-consensus = { git = "https://github.com/polytope-labs/ethereum-consensus", branch = "main", default-features = false }
ssz-rs = { git = "https://github.com/polytope-labs/ssz-rs", branch = "main" , default-features = false }
log = { version = "0.4.17", default-features = false }

[features]
default = ["std"]
std = [
    "ssz-rs/std",
    "log/std"
]
testing = ["sync-committee-primitives/testing"]
