name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown

      - name: Run cargo check
        run: cargo check

      - name: Build `no-std`
        run: |
          cargo +nightly check -p sync-committee-verifier --no-default-features --target=wasm32-unknown-unknown --verbose

  test:
    name: Test Suite
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
    env:
      TUID: 123
    steps:
      - name: set UID env
        run: |
          echo $UID
          echo "TUID=$UID" >> $GITHUB_ENV

      - name: Checkout sources
        uses: actions/checkout@master

      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install protoc
        run: |
          sudo apt update
          sudo apt install protobuf-compiler

      - name: Clone eth-pos-devnet repository
        run: |
          git clone https://github.com/polytope-labs/eth-pos-devnet.git
          cd eth-pos-devnet
          docker compose up &
          ../scripts/wait_for_tcp_port_opening.sh localhost 3500 
          ../scripts/wait_for_tcp_port_opening.sh localhost 8545 

      - name: Run all tests
        run: |
          cargo +nightly test -p sync-committee-prover -- --nocapture
